import type { RowDataPacket } from 'mysql2/promise';

export type SusarEuRow = RowDataPacket & {
  id: number;
  master_id: number;
  caseid: number;
  specificcaseid: string;
  dlpversion: number;
  creationdate: string | Date;
  statusdate: string | Date;
  studytitle: string;
  sponsorstudynumb: string;
  num_eudract: string;
  pays_etude: string;
  type_susar: string;
  indication: string;
  indication_eng: string;
  product_name: string;
  substance_name: string;
  commentaire: string;
  date_evaluation: string | Date;
  narratif: string;
  pays_survenue: string;
  date_aiguillage: string | Date;
  date_import: string | Date;
  nb_medic_suspect: number;
  patient_age_group: string;
  patient_age: number;
  patient_age_unit_label: string;
  is_case_serious: string;
  seriousness_criteria: string;
  patient_sex: string;
  world_wide_id: string;
  seriousness_criteria_brut: string;
  utilisateur_evaluation: string;
  utilisateur_aiguillage: string;
  utilisateur_import: string;
  created_at: string | Date;
  updated_at: string | Date;
  priorisation: string;
  cas_ime: number;
  cas_dme: number;
  cas_europe: number;
  cas_susar_eu_v1: number;
  date_reprise_susar_eu_v1: string | Date;
  id_ctll: number;
  import_ctll_id: number;
  ev_safety_report_identifier: string;
  receive_date: string | Date;
  receipt_date: string | Date;
  gateway_date: string | Date;
  initials_height_weight: string;
  birth_date: string;
  primary_source_qualification: string;
  parent_child: string;
  narratif_nb_caractere: number;
  icsr_form_link: string;
  e2_b_link: string;
  complete_narrative_link: string;
  sender: string;
};
